server:
  port: 9009
spring:
  application:
    name: tensquare_rabbitmq
  rabbitmq:
    host: tensquare

aliyun:
  sms:
    accessKeyId: LTAI4FbtopGZQhuM5L74mV2A
    accessKeySecret: wGDeyoX1CftOXRgUXu74bHZByuTTSR
    template_code: SMS_182679179
    sign_name: 点餐跑腿