server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/li_yunhe/tensquare_dev.git
  rabbitmq:
    host: 192.168.38.144
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
